"""Auto-translate judged deliverables from ES to EN.

Adapted from rcj-2026-rescue-line-iita-salta-robocup.
Fuente de verdad: docs/competencia/ (ES). Se barren DOS directorios (el anterior y el nuevo):
  - docs/official/     (anterior/legacy)  -> docs/official/en/
  - docs/competencia/  (nuevo/vigente)    -> docs/competencia/en/
Cada uno se traduce a su propio subdir en/ (auto-generado; NO editar a mano).

OPCIÓN A (2026-06-05): el pipeline se repuntó de docs/official/ a docs/competencia/.
2026-06-13: se BARREN AMBOS (anterior + nuevo) — ver SOURCE_DIRS abajo.
Solo se traducen los DELIVERABLES juzgables (allowlist abajo). Los docs INTERNOS de
trabajo (MEJORAS-PENDIENTES, RUBRICA-COBERTURA, CUESTIONARIO-DATOS-EQUIPO,
BOM-COSTOS-TEMPLATE, README) NO se traducen. Para sumar un deliverable nuevo,
agregalo al set DELIVERABLES.

Regla del equipo: el INGLÉS es AUTO-GENERADO; NO editar a mano docs/competencia/en/.
Editar siempre el español (fuente de verdad).

Requires: OPENAI_API_KEY environment variable (GitHub Actions secret).
"""
import os
import pathlib
import re
from openai import OpenAI

# Barremos el ANTERIOR (docs/official, legacy) y el NUEVO (docs/competencia, fuente de
# verdad vigente). Cada source_dir escribe a su propio <source_dir>/en.
# 2026-06-13: se sumó docs/official al barrido a pedido del equipo ("incluir el anterior y
# el nuevo"); hoy docs/official solo tiene un doc de prueba (ningún deliverable de la
# allowlist) → en la práctica no produce nada, pero queda cubierto por si vuelve a usarse.
SOURCE_DIRS = [
    pathlib.Path("docs/official"),     # anterior (legacy)
    pathlib.Path("docs/competencia"),  # nuevo (deliverables vigentes — fuente de verdad)
]

# Allowlist: SOLO estos .md (top-level de docs/competencia) se traducen a en/.
# Agregá acá un deliverable nuevo cuando corresponda.
DELIVERABLES = {
    "BOM.md",
    "ENTREVISTA-PREP.md",
    "ONE-PAGER.md",
    "POSTER.md",
    "TDP.md",
    "VIDEO-GUION.md",
    "USO-DE-IA.md",
}

AUTO_HEADER = (
    "<!-- AUTO-GENERATED FILE – DO NOT EDIT.\n"
    "     Source: docs/competencia (Spanish is source of truth)\n"
    "     Generated by GitHub Actions (scripts/translate_docs.py). Edit the ES file instead.\n"
    "-->\n\n"
)


def strip_existing_auto_header(text: str) -> str:
    return re.sub(r"^<!-- AUTO-GENERATED FILE – DO NOT EDIT\.[\s\S]*?-->\n\n", "", text)


def translate_markdown(client: OpenAI, md: str) -> str:
    prompt = (
        "Translate this Markdown from Spanish to English.\n"
        "- Preserve Markdown formatting exactly.\n"
        "- Do NOT translate code blocks (``` ... ```), inline code (`...`), file paths, or URLs.\n"
        "- Keep technical terms consistent (e.g. 'arquero' -> 'goalkeeper', 'delantero' -> 'striker').\n"
        "- This is RoboCup Junior Soccer Open documentation.\n"
        "Return only the translated Markdown.\n\n"
        "Markdown:\n"
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a careful technical translator for robotics competition documentation."},
            {"role": "user", "content": prompt + md},
        ],
        temperature=0.2,
    )
    return resp.choices[0].message.content


def main():
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("ERROR: OPENAI_API_KEY is missing. Configure it as a GitHub Actions secret.")

    client = OpenAI(api_key=api_key)

    if not any(d.exists() for d in SOURCE_DIRS):
        raise SystemExit(f"ERROR: ninguno de los SOURCE_DIRS existe: {SOURCE_DIRS}")

    # Barre el ANTERIOR y el NUEVO; cada uno escribe a su propio <dir>/en.
    # Solo top-level *.md (NO recursivo: no entra a en/ ni assets/), filtrado por allowlist.
    translated_any = False
    for source_dir in SOURCE_DIRS:
        if not source_dir.exists():
            print(f"Skip (no existe): {source_dir}")
            continue

        target_dir = source_dir / "en"
        target_dir.mkdir(parents=True, exist_ok=True)

        for src in sorted(source_dir.glob("*.md")):
            if src.name not in DELIVERABLES:
                print(f"Skip (no es deliverable): {source_dir}/{src.name}")
                continue

            src_text = src.read_text(encoding="utf-8")
            if not src_text.strip():
                continue

            print(f"Translating {source_dir}/{src.name}...")
            translated = translate_markdown(client, src_text)

            dst = target_dir / src.name
            dst.write_text(AUTO_HEADER + strip_existing_auto_header(translated), encoding="utf-8")
            print(f"  -> {dst}")
            translated_any = True

    if not translated_any:
        print("No deliverables to translate.")


if __name__ == "__main__":
    main()
